// IngredientsDB
const FETCH_INGREDIENTS_FROM_DB = "FETCH_INGREDIENTS_FROM_DB";
const SET_LOADING = 'SET_LOADING';
const CLEAR_LOADING = 'CLEAR_LOADING';
const SET_INIT_INGREDIENTS = "SET_INIT_INGREDIENTS";
const FETCH_BASEPRICE_FROM_DB = "FETCH_BASEPRICE_FROM_DB";
const SET_INIT_BASEPRICE = "SET_INIT_BASEPRICE";

// Ingredients
const SET_INIT_TOTALPRICE = "SET_INIT_TOTALPRICE";
const ADD_INGREDIENT = "ADD_INGREDIENT";
const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
const CLEAR_INGREDIENTS = "CLEAR_INGREDIENTS";

// cart
const ADD_CART_ITEM = "ADD_CART_ITEM"
const REMOVE_CART_ITEM = "REMOVE_CART_ITEM"
const CLEAR_CART = "CLEAR_CART"

// Users
const SET_CURRENT_USER = "SET_CURRENT_USER"
const SET_CURRENT_USER_ERROR = "SET_CURRENT_USER_ERROR"
const SET_CURRENT_USER_TO_EMPTY = "SET_CURRENT_USER_TO_EMPTY"
const SET_USER_LOADING = "SET_USER_LOADING"
const CLEAR_USER_LOADING = "CLEAR_USER_LOADING"

//save order
const SAVE_ORDER = "SAVE_ORDER"
const SET_ORDER_LOADING = "SET_ORDER_LOADING"
const CLEAR_ORDER_LOADING = "CLEAR_ORDER_LOADING"
const SET_ORDER_STATUS = "SET_ORDER_STATUS"
const CLEAR_ORDER_STATUS = "CLEAR_ORDER_STATUS"

// fetch orders
const FETCH_ORDERS = "FETCH_ORDERS"
const SET_FETCHORDERS_LOADING = "SET_FETCHORDERS_LOADING"
const CLEAR_FETACHORDERS_LOADING = "CLEAR_FETACHORDERS_LOADING"
const SET_ORDERS = "SET_ORDERS"

export {FETCH_INGREDIENTS_FROM_DB,
        SET_LOADING,
        CLEAR_LOADING,
        SET_INIT_INGREDIENTS,
        FETCH_BASEPRICE_FROM_DB,
        SET_INIT_BASEPRICE,
        SET_INIT_TOTALPRICE,
        ADD_INGREDIENT,
        REMOVE_INGREDIENT,
        CLEAR_INGREDIENTS,
        ADD_CART_ITEM,
        REMOVE_CART_ITEM,
        CLEAR_CART,
        SET_CURRENT_USER,
        SET_CURRENT_USER_ERROR,
        SET_CURRENT_USER_TO_EMPTY,
        SET_USER_LOADING,
        CLEAR_USER_LOADING,
        SAVE_ORDER,
        SET_ORDER_LOADING,
        CLEAR_ORDER_LOADING,
        SET_ORDER_STATUS,
        CLEAR_ORDER_STATUS,
        FETCH_ORDERS,
        SET_FETCHORDERS_LOADING,
        CLEAR_FETACHORDERS_LOADING,
        SET_ORDERS};
