// Ingredients
const FETCH_INGREDIENTS_FROM_BACKEND = "FETCH_INGREDIENTS_FROM_BACKEND";
const ADD_INGREDIENT = "ADD_INGREDIENT";
const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
const CLEAR_INGREDIENTS = "CLEAR_INGREDIENTS";

// Users

//Orders

export {FETCH_INGREDIENTS_FROM_BACKEND,ADD_INGREDIENT,REMOVE_INGREDIENT,CLEAR_INGREDIENTS};
