// IngredientsDB
const FETCH_INGREDIENTS_FROM_DB = "FETCH_INGREDIENTS_FROM_DB";

// Ingredients
const SET_INIT_TOTALPRICE = "SET_INIT_TOTALPRICE";
const ADD_INGREDIENT = "ADD_INGREDIENT";
const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
const CLEAR_INGREDIENTS = "CLEAR_INGREDIENTS";

// Users

//Orders

export {FETCH_INGREDIENTS_FROM_DB,
        SET_INIT_TOTALPRICE,
        ADD_INGREDIENT,
        REMOVE_INGREDIENT,
        CLEAR_INGREDIENTS};
